#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use CodeSnake\Console\RunCodeSnake;
use CodeSnake\Snake\SnakeRowFormatter;
use Symfony\Component\Console\Application;

$container = new League\Container\Container;
$container->add(SnakeRowFormatter::class);

$application = new Application;

$application->add(new RunCodeSnake($container->get(SnakeRowFormatter::class)));

$application->run();